apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: idp-platform
      team: platform
    includeSelectors: true
images:
  - name: web
    newName: 600406561872.dkr.ecr.us-east-1.amazonaws.com/idp-dev/web
    newTag: ec98f17c55d87a94da7eb8c00530fc38950dde42