name: CI
on: 
 push: 
    branches: [main]

permissions:
    id-token: write
    contents: read 

env: 
  AWS_REGION: us-east-1
  ECR_REPOSITORY: idp-dev/web
  ROLE_ARN: arn:aws:iam::600406561872:role/idp-github-actions

jobs:
  build-and-push: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Semgrep SAST scan
        run: |
            pip install semgrep
            semgrep scan --config "p/default" app/

      - name: Login in to AWS via OIDC 
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{env.ROLE_ARN}}
            aws-region: ${{env.AWS_REGION}}

      - name: Login in Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Compute image name
        run: echo "IMAGE=${{steps.ecr.outputs.registry}}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> "$GITHUB_ENV"
    
      - name: Build the image 
        run: docker build -t "$IMAGE" ./app

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true 
          exit-code: "0"

      - name: Push the image
        run: docker push "$IMAGE"